### ISSUE TITLE
[Feature Request] Support select pane after starting new session

### ISSUE THREAD

**Issue by moonlight8978** [ck3mp3r/laio-cli#157]
## Overview
Hi, I've just found this awesome project, and it fits my workflow very well
It would be great if a specific pane can be selected by default after starting a new session

## Detailed Description
Below is an example of my session configuration

```yaml
# .laio.yaml
name: dotfiles
windows:
  - name: code
    panes: 
      - flex: 5 # main editor
        commands:
          - command: nvim .
      - flex: 3 # terminal
```
It's a bit inconvenience because the terminal pane is always selected first, therefore I have to switch to the editor pane manually

It would be great if we add a `focus` on the pane config, so the editor pane will be automatically selected after starting session
```yaml
panes:
  - flex: 5
    focus: true
  - flex: 3
```

This is just the rough idea, we may have more work to do with window, etc...

## Benefits
A specific pane can be selected by default without manual operations

## Alternatives
I'm currently using tmux hook to switch to editor pane (usually pane 0), but it fails if the editor pane is not 0 
```
set-hook -g client-attached 'run-shell "tmux select-pane -t 0"'
```

## Additional Context
Add any other context about the feature request here.
