### ISSUE TITLE
fails if window name has space in it, error message does not validate

### ISSUE THREAD

**Issue by shedali** [ck3mp3r/laio-cli#69]
```yaml
name: xxx

path: xxx

windows:
  - name: hello world
```

```bash
[2024-01-29T11:31:55Z ERROR laio::commands::cli] Command failed: tmux select-layout -t component-library:component-library:2.0 "dade,181x90,0,0"
[2024-01-29T11:31:55Z ERROR laio::commands::cli] Shutting down session: component-library
```

0.7.6 installed via flakehub: `fh add "ck3mp3r/laio-cli/0.7.6"`
